name: ci
env:
  build_version: 0.1.${{github.run_number}}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        dotnet restore samples/**/*.csproj
        dotnet restore src/**/*.csproj
        dotnet restore tests/**/*.csproj
    - name: Build
      run: |
        dotnet build samples/**/*.csproj --configuration Release --no-restore
        dotnet build src/**/*.csproj --configuration Release --no-restore
        dotnet build tests/**/*.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/**/*.csproj --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/EntityFrameworkCore.MergeExtension/EntityFrameworkCore.MergeExtension.csproj -o packaged -c Release -p:PackageVersion=$build_version
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: packaged
        path: packaged
    - name: Push
      env:
        nuget_api_key: ${{ secrets.nuget_api_key }}
      run: dotnet nuget push packaged/EntityFrameworkCore.MergeExtension.$build_version.nupkg -k $nuget_api_key -s https://api.nuget.org/v3/index.json
