name: .NET Core
env:
  build_version: 0.0.${{ GITHUB_RUN_ID }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        dotnet restore samples/**/*.csproj
        dotnet restore src/**/*.csproj
        dotnet restore tests/**/*.csproj
    - name: Build
      run: |
        dotnet build samples/**/*.csproj --configuration Release --no-restore
        dotnet build src/**/*.csproj --configuration Release --no-restore
        dotnet build tests/**/*.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/**/*.csproj --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/EntityFrameworkCore.MergeExtension/EntityFrameworkCore.MergeExtension.csproj -o packaged -c Release -p:PackageVersion=$build_version
